name: Delta Deploy - XXXPROD

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths: 'mytest/main/default/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # using fetch-depth = 0 to make the entire history of commits available
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    
    # Install SFDX CLI
    - name: Installations and Support Tasks
      run: |
        echo "commit=$(cat deploymentCommit.txt)" >> $GITHUB_ENV
        npm install sfdx-cli --global
        echo y | sfdx plugins:install sfdx-git-delta
        openssl enc -nosalt -aes-256-cbc -d -in buildfiles/server.key.enc -out server.key -base64 -K ${{secrets.PRODKEY}} -iv ${{secrets.PRODIV}}

    # Authorize SF Org
    - name: Authorize Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEPRODUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEPRODINSTANCEURL }}
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile server.key --username $USERNAME --instanceurl $INSTANCE_URL -a prod
    
    - name: Create Delta Changes Package
      run: |
        sfdx sgd:source:delta --output ./ --source=mytest/main/default/ --to HEAD --from ${{env.commit}} 
        cat package/package.xml 

    # Deploy directly to Org; use alias as per org
    - name: Validate Package Changes
      run: |
        sfdx force:source:deploy -x package/package.xml -u prod -c | head -2 | tail -1 | cut -c12-30 > deployid.txt
        echo "jobid=$(cat deployid.txt)" >> $GITHUB_ENV

    # Deploy directly to Org; use alias as per org
    - name: Deploy Package Changes
      run: sfdx force:source:deploy -x package/package.xml -u prod -q ${{env.jobid}}
        
    - name: Store SHA 
      run: |
        echo $GITHUB_SHA > ./deploymentCommit.txt
        git config --global user.email "mehta.jay223@gmail.com"; git config --global user.name "JayMehta"
        git add deploymentCommit.txt ; git commit -m "Last deployed Commit SHA updated"; git push
