name: Delta Deploy - XXXPROD

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths: ['mytest/main/default/**','.github/workflows/delta.yml']
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # using fetch-depth = 0 to make the entire history of commits available
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/cache@v3
      with: 
        path: $~/sfdc
        key: sfdx-eu1rbd-v1
    
    # Install SFDX CLI echo "GH_TOKEN=${{ secrets.token }}" >> $GITHUB_ENV
    - name: Installations and Support Tasks
      run: |
        echo "commit=${{ secrets.MYSECRET }}" >> $GITHUB_ENV
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.143.0/7049747/sfdx-v7.143.0-7049747-linux-x64.tar.xz
        mkdir ~/sfdx
        tar xJf sfdx-v7.143.0-7049747-linux-x64.tar.xz -C ~/sfdx --strip-components 1
    - name: Test
      run: |
        PATH="$PATH":~/sfdx/bin
        echo $PATH
        echo "SAving this to the github path variable"
        echo "$PATH" >> $GITHUB_PATH 
        sfdx --version
        openssl enc -nosalt -aes-256-cbc -d -in buildfiles/server.key.enc -out server.key -base64 -K ${{secrets.PRODKEY}} -iv ${{secrets.PRODIV}}
    - run: echo $PATH

    - name: isntall plugin
      run: |
        sfdx --version
        echo y | sfdx plugins:install sfdx-git-delta

    # Authorize SF Org
    - name: Authorize Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEPRODUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEPRODINSTANCEURL }}
      run: PATH="$PATH":~/sfdx/bin;sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile server.key --username $USERNAME --instanceurl $INSTANCE_URL -a prod
    
    - name: Create Delta Changes Package
      run: |
        PATH="$PATH":~/sfdx/bin
        sfdx sgd:source:delta --output ./ --source=mytest/main/default/ --to HEAD --from ${{env.commit}} 
        cat package/package.xml 
        cat destructiveChanges/destructiveChanges.xml
        cat package/package.xml | head -3 | tail -1 > packageline3.txt
        cat destructiveChanges/destructiveChanges.xml | head -3 | tail -1 > destpackageline3.txt
        echo "precednt=$(cat packageline3.txt)" >> $GITHUB_ENV
        echo "destprecednt=$(cat destpackageline3.txt)" >> $GITHUB_ENV

    # Deploy directly to Org; use alias as per org
#     - name: Deploy Package Changes
#       if: precednt
#       run: sfdx force:source:deploy -x package/package.xml -u prod 
        
#     - name: Store SHA 
#       run: |
#         gh auth login --with-token <<< "${{ secrets.token }}"
#         gh secret set MYSECRET --body $GITHUB_SHA

        
