name: Delta Deploy - FULL

# Controls when the workflow will run
on:
  push:
    branches: [ FULL ]
    #paths: 'force-app/main/default/**'

  pull_request:
    branches: [ FULL ]
    #paths: 'force-app/main/default/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # using fetch-depth = 0 to make the entire history of commits available
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: |
        echo "commit=$(cat deploymentCommit.txt)" >> $GITHUB_ENV
        npm install sfdx-cli --global
        echo y | sfdx plugins:install sfdx-git-delta

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.FULL_CLIENTID }}
        USERNAME: ${{ secrets.FULL_USERNAME }}
        INSTANCE_URL: ${{ secrets.FULL_LOGININSTANCE}}
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a full
    
    - name: Create Delta Changes Package
      run: |
        sfdx sgd:source:delta --output ./ --to HEAD --from HEAD^ --source force-app/
        cat package/package.xml 

    # Deploy directly to Org; use alias as per org, no real implications
    - name: Deploy Package Changes
      run: sfdx force:source:deploy -x package/package.xml -u full 
        
    - name: Store SHA 
      run: |
        echo $GITHUB_SHA > ./deploymentCommit.txt
        git config --global user.email "mehta.jay223@gmail.com"; git config --global user.name "JayMehta"
        git add deploymentCommit.txt ; git commit -m "Last deployed Commit SHA updated"; git push