name: View Delta for Destructive

# Controls when the workflow will run
on:
  workflow_dispatch: 

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # using fetch-depth = 0 to make the entire history of commits available
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: |
        echo "commit=$(cat deploymentCommit.txt)" >> $GITHUB_ENV
        npm install sfdx-cli --global
        echo y | sfdx plugins:install sfdx-git-delta
        
    - name: Create Delta Changes Package
      run: |
        sfdx sgd:source:delta --output ./ --source=mytest/main/default/ --to HEAD --from ${{env.commit}}
        cat destructiveChanges/destructiveChanges.xml
