name: Test in VM

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    #paths: 'mytest/main/default/**'

  pull_request:
    branches: [ master ]
    #paths: 'mytest/main/default/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # using fetch-depth = 0 to make the entire history of commits available
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'

    - name: Print Commit ID Prev vs. Commit ID latest
      run: |
        cat deploymentCommit.txt
        cat deploymentCommit.txt >> $GITHUB_ENV 
        echo "${{ env.commit }}"

    


      
      
