name: test of package

# Controls when the workflow will run
on:
  push:
    branches: [ sfdxformat ]
    #paths: 'mytest/force-app/main/default/**'
  pull_request:
    branches: [ sfdxformat ]
    #paths: 'mytest/force-app/main/default/**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: |
        npm install sfdx-cli --global
        echo y | sfdx plugins:install sfdx-git-delta

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEPRODUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEPRODINSTANCEURL }}
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a prod

    # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: |
        mkdir output
        sfdx sgd:source:delta --from "83b3f692660359c486f6bfa94496da27fd46d356" --to "a77a04bdab03a13e7d19d2b37088a993b5775301" 

    - name: package generated display
      run: cat output/package/package.xml

    - name: deploy to org
      run: sfdx force:mdapi:deploy -d "output/package/package.xml"
