name: test of package

# Controls when the workflow will run
on:
  push:
    branches: [ sfdxformat ]
    #paths: 'mytest/force-app/main/default/**'
  pull_request:
    branches: [ sfdxformat ]
    #paths: 'mytest/force-app/main/default/**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: |
        npm install sfdx-cli --global
        echo y | sfdx plugins:install sfdx-git-delta

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEPRODUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEPRODINSTANCEURL }}
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a prod

    # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx sgd:source:delta --to "e8f60a137c62beac27856082afc8a5c60d12fe91" --from "cb9a45bea8e9195c7de218f17d2ff9d418483512" --output .

    - name: package generated display
      run: cat package/package.xml

    - name: deploy to org
      run: sfdx force:source:deploy -x package/package.xml -u prod
