name: Test

on:
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:      
    - run: echo "Jay is great" >> chamberlain.txt
        
    - name: Storing Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Jay test
        path: ./chamberlain.txt

